### ISSUE TITLE
Fixing President List

### ISSUE THREAD

**Issue by imamsutono** [imamsutono/SimpleRecyclerView#1]
president data is wrong, can anyone help?
![imam sutono android recyclerview](https://user-images.githubusercontent.com/17371955/32203426-ce1ab234-be15-11e7-819a-55307dc490f4.jpeg)

**Comment by sathyapriya31** [comment]
@imamsutono what is the issue you currently facing? can you please explain

**Comment by imamsutono** [comment]
@sathyapriya31 last President Data is wrong, and you can fix it with delete it
